serve:
    dx serve

release:
    dx build --release

npm-install:
    cd static/css && just npm-install

build-classes:
    cd css && just build-classes

watch-classes:
    cargo watch -w src/ -s "clear-buffer && cargo build && just build-classes"
