serve:
    dx serve

release:
    dx build --release

npm-install:
    cd static/css && npm install

build-classes:
    cargo test --features "web build-classes"
    echo "]" >> ../../classes.rs
    mv -v ../../classes.rs .

watch-classes:
    cargo watch -w src/ -s "just build-classes && cargo build"
